version: '3'

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    networks:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

  # email/password for admin dasboard:
  # pgadmin4@pgadmin.org / admin
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
